### ISSUE TITLE
Deploy your own Vercel instance

### ISSUE THREAD

**Issue by cy-Yin** [ryo-ma/github-profile-trophy#383]
I just deployed my own instance and would like to share my experience.
The final result can be viewed at @cy-Yin : https://github.com/cy-Yin

*Similar to [github-readme-stats/deploy-on-your-own](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own), with some details modified.*

1. get your Personal Access Token (PAT)
For deploying your own instance of GitHub Readme Stats, you will need to create a GitHub Personal Access Token (PAT).

- Go to [Account -> Settings -> Developer Settings -> Personal access tokens -> Tokens (classic)](https://github.com/settings/tokens).
- Click on `Generate new token` -> `Generate new token (classic)`.
- Scopes to select:
  - repo
  - read:user
- Click on Generate token and copy it (**Note that this token is not visible after refreshing the website**).

2.  Vercel deployment

-  Go to [vercel.com](https://vercel.com/).
- Click on `Log in`.
-  Sign in with GitHub by pressing `Continue with GitHub`.
- Sign in to GitHub and allow access to all repositories if prompted.
- Fork this repo.
- Go back to your [Vercel dashboard](https://vercel.com/dashboard).
- To import a project, click the `Add New...` button and select the `Project` option.
- Click the `Continue with GitHub` button, search for the required Git Repository and import it by clicking the `Import` button. Alternatively, you can import a Third-Party Git Repository using the `Import Third-Party Git Repository ->` link at the bottom of the page.
- Create a Personal Access Token (PAT) as described in the [previous section](#first-step-get-your-personal-access-token-pat).
- Add the PAT as an `environment variable` named `GITHUB_TOKEN1` 

> [!NOTE]
> **Very important: Note that in the [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) repo, the  `environment variable` is named as `PAT_1` as shown below. However, in this repo one must name this  `environment variable` as `GITHUB_TOKEN1`. I have tried `GITHUB_TOKEN`, `PAT_1`, etc., only the `GITHUB_TOKEN1` works.**

![](https://files.catbox.moe/0yclio.png)
- Click deploy, and you're good to go. See your domains to use the API!

**Comment by ikostan** [comment]
I followed all the steps listed above by @cy-Yin. Not sure why but I am getting 404 after deployment on Vercel, see screenshot below

<img width="965" height="246" alt="Image" src="https://github.com/user-attachments/assets/23cf83fe-6ebf-4b20-9fc7-94c1821c51fd" />

**Comment by cy-Yin** [comment]
> I followed all the steps listed above by [@cy-Yin](https://github.com/cy-Yin). Not sure why but I am getting 404 after deployment on Vercel, see screenshot below
> 
> <img alt="Image" width="965" height="246" src="https://private-user-images.githubusercontent.com/20955183/524608977-23cf83fe-6ebf-4b20-9fc7-94c1821c51fd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUzNjU4MzksIm5iZiI6MTc2NTM2NTUzOSwicGF0aCI6Ii8yMDk1NTE4My81MjQ2MDg5NzctMjNjZjgzZmUtNmViZi00YjIwLTlmYzctOTRjMTgyMWM1MWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEwVDExMTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjYyMWFlNzYxMjNmNTI4YTdhOWNhY2I0YTM0NGY1MjE4MGI0Yjg4YmZiZTc4ZWE2MzE0YjFhMjk3M2Q3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WYuyuS1JCRZSAIBPMdoVdrTsoFxeGA2y276xjQOUfdw">

Don't worry — I ran into this issue when I deployed as well. I also clicked into other people's instances and saw the same page. For example, @codeztech-atique's deployed endpoint: https://github-profile-trophy-roan.vercel.app/. But this doesn't affect using it in your `README.md`.

**Comment by minhd-vu** [comment]
> I followed all the steps listed above by [@cy-Yin](https://github.com/cy-Yin). Not sure why but I am getting 404 after deployment on Vercel, see screenshot below
> 
> <img alt="Image" width="965" height="246" src="https://private-user-images.githubusercontent.com/20955183/524608977-23cf83fe-6ebf-4b20-9fc7-94c1821c51fd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU0MTYyNzksIm5iZiI6MTc2NTQxNTk3OSwicGF0aCI6Ii8yMDk1NTE4My81MjQ2MDg5NzctMjNjZjgzZmUtNmViZi00YjIwLTlmYzctOTRjMTgyMWM1MWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjExVDAxMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZGY4MDU2NmJhYjkxNWU0MzE5MWEyMTI5Y2I1YjBmMjJlNjdhZjE3NGZiYzkzZDA5MDI2Njg4MjAyM2JhOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.09C4uv11HSd2obu3tL_uNdHp_IV12Hre-NgxQchdRoo">

I had to set the `GITHUB_TOKEN1` env var in vercel to get it to work. Hope this helps 😄

**Comment by iSpeakNerd** [comment]
Thanks for putting this together @cy-Yin, I got my vercel deployment working with my PAT but it still doesn't render the trophy image correctly on my readme

edit: i think the [vercel login page](https://vercel.com/docs/deployment-protection/methods-to-protect-deployments/vercel-authentication#managing-vercel-authentication) is blocking requests from github, preventing readme.md rendering

edit2: yup that was it

**Comment by ArtofBugs** [comment]
Thank you, this worked for me!

**Comment by 1Dedios** [comment]
THIS NEEDS TO BE PART OF THE OFFICIAL DOCS FOR THIS REPO
